### ISSUE TITLE
Error "mDNS: failed to join multicast group" on WSL in Windows

### ISSUE THREAD

**Issue by master-hax** [pion/mdns#26]
https://github.com/pion/mdns/blob/4f64fff267575a320f9f33a9c9bdcbbbe4a57d72/errors.go#L6
https://github.com/pion/mdns/blob/b37c5ea9873852016bf183e1333ce8b6dd7d9ae9/conn.go#L66

I am seeing this log message from the code fragment

```
import ( "github.com/pion/webrtc/v2" )
func doWebRTC() {
    _, err := webrtc.NewPeerConnection(webrtc.Configuration{})
    if err != nil {
        log.Println("error while starting RTC server:", err)
    }
}
go doWebRTC()
```

I am not sure what is causing it but I have seen it referenced in at least one other issue: https://github.com/pion/example-webrtc-applications/issues/27

**Comment by Sean-Der** [comment]
Hey @master-hax 

This should be fixed now! mDNS should be opportunistic, but we accidentally made it mandatory. https://github.com/pion/ice/pull/184 is the PR that fixed the root issue, and we released a new version of `pion/webrtc` with it.

sorry for taking so long on this, thanks for using Pion :)
