### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by vtolstov** [pion/mdns#69]
Please add ipv6 support

**Comment by edaniels** [comment]
we could consider adopting some code from zeroconf which does a fair bit of this https://github.com/grandcat/zeroconf but it does have its own quirks.

**Comment by TA2k** [comment]
Do you have an update on this because in IPv4 mode no multiple mDNS server are possible in the same network

**Comment by edaniels** [comment]
There's some work in https://github.com/pion/mdns/pull/173 that gets us a lot closer. Once that's in, I may just pick this up.
