### ISSUE TITLE
Querying does not work for cases when advertising is delegated to another host.

### ISSUE THREAD

**Issue by akamensky** [pion/mdns#93]
### Your environment.
  - Version: v0.0.5
  - Browser: N/A
  - Other Information - N/A

### What did you do?
I have a code that advertises A records on behalf of other hosts. Simple code to do that is (this code runs on a host with a different IP address):

```go
package main

import (
	"github.com/davecheney/mdns"
	"fmt"
	"time"
)

func main() {
	err := mdns.Publish("test.local 60 IN A 10.0.1.0")
	if err != nil {
		panic(err)
	}
	fmt.Println("ok")
	time.Sleep(60 * time.Minute)
}
```

Then query it using code as in examples:

```go
package main

import (
	"context"
	"fmt"
	"net"

	"github.com/pion/mdns"
	"golang.org/x/net/ipv4"
)

func main() {
	addr, err := net.ResolveUDPAddr("udp", mdns.DefaultAddress)
	if err != nil {
		panic(err)
	}

	l, err := net.ListenUDP("udp4", addr)
	if err != nil {
		panic(err)
	}

	server, err := mdns.Server(ipv4.NewPacketConn(l), &mdns.Config{})
	if err != nil {
		panic(err)
	}
	answer, src, err := server.Query(context.TODO(), "test.local")
	if err != nil {
		panic(err)
	}
	fmt.Println(answer)
	fmt.Println(src)
	fmt.Println(err)
}
```

### What did you expect?

Querying using this library should work. It works using avahi client and it works using macos dns-sd. I expect that while the above code is running, querying using this library for "test.local" returns correct result.

### What happened?

It hangs indefinitely.

**Comment by Sean-Der** [comment]
If you apply https://github.com/pion/mdns/pull/70 does it work?

Most of my attention is on https://github.com/pion/webrtc, but will try my best to get this working!

**Comment by akamensky** [comment]
No, #70 does not fix it. I checked and the code returns here conn.go#L297 For some reason it sees it as empty response. Which it is not.

**Comment by edaniels** [comment]
@akamensky if you're still interested, can you check if this is still an issue?

**Comment by edaniels** [comment]
Verified #176 fixes this
